# Increase memory available to Gradle (needed for genSources/decompile).
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.14.0
group=com.jg

# Mod metadata
archives_base_name=To-Do list
mod_id=memo
mod_name=备忘录
mod_authors=JG
mod_description=在游戏内随手记录待办事项的备忘录 Mod，按 M 键打开。
mod_license=MIT

# Dependencies
modmenu_version=20.0.1

# Dependencies
fabric_api_version=0.158.0+26.2
